name: 'Resolve Session'
description: 'Determines session context and handles email events'
outputs:
  issue_number:
    description: 'The issue number for the session'
    value: ${{ steps.resolve.outputs.issue_number }}
  user_email:
    description: 'Email of the user'
    value: ${{ steps.resolve.outputs.user_email }}
  user_message:
    description: 'The message content'
    value: ${{ steps.resolve.outputs.user_message }}

runs:
  using: "composite"
  steps:
    - name: Resolve Context
      uses: actions/github-script@v7
      id: resolve
      with:
        script: |
          const eventName = context.eventName;
          const action = context.payload.action;
          
          let issue_number, user_email, user_message;

          if (action === 'email_session_start') {
            const payload = context.payload.client_payload || {};
            const subject = payload.subject || 'New Kinen Session';
            const body = payload.body || '(No content)';
            const from = payload.from || 'unknown';

            console.log('Email Session Start:', { subject, from });

            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: subject,
              body: '**From:** ' + from + '\n\n---\n\n' + body,
              labels: ['kinen-session']
            });

            issue_number = issue.data.number;
            user_email = from;
            user_message = body;
            console.log('Created issue #' + issue_number);

          } else if (action === 'email_session_continue') {
            const payload = context.payload.client_payload || {};
            issue_number = payload.issue_number;
            const body = payload.body || '(No content)';
            const from = payload.from || 'unknown';

            console.log('Email Session Continue:', { issue_number });

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt(issue_number),
              body: '**From:** ' + from + '\n\n---\n\n' + body
            });

            user_email = from;
            user_message = body;
            console.log('Added comment to issue #' + issue_number);

          } else if (eventName === 'issue_comment') {
            const issue = context.payload.issue;
            const comment = context.payload.comment;
            
            issue_number = issue.number;
            user_email = comment.user.login + '@github';
            user_message = comment.body;
            
            console.log('Processing comment on issue #' + issue_number);
          } else {
             console.log('Unknown event context');
          }

          core.setOutput('issue_number', issue_number);
          core.setOutput('user_email', user_email);
          core.setOutput('user_message', user_message);
