name: 'Run Agent'
description: 'Runs the AI agent (Aider)'
inputs:
  model:
    required: true
  methodology_file:
    required: true
  user_message:
    required: true
  openrouter_api_key:
    required: false
  openai_api_key:
    required: false
  gemini_api_key:
    required: false
  anthropic_api_key:
    required: false

runs:
  using: "composite"
  steps:
    - name: Run Aider
      shell: bash
      env:
        OPENROUTER_API_KEY: ${{ inputs.openrouter_api_key }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
      run: |
        echo "🤖 Running Aider with model: ${{ inputs.model }}"

        # Run Aider
        aider \
          --model "${{ inputs.model }}" \
          --read "${{ inputs.methodology_file }}" \
          --message "${{ inputs.user_message }}" \
          --yes-always \
          --no-auto-commits \
          2>&1 | tee /tmp/aider-output.log

        if [ ${PIPESTATUS[0]} -ne 0 ]; then
          echo "❌ Aider failed"
          exit 1
        fi
